version: "3.6"

services:
    server:
        image: nginx:latest
        container_name: ${APP_NAME}-nginx
        volumes:
            - ./:/var/www
            - ./.docker/nginx/conf.d:/etc/nginx/conf.d/
        ports:
            - 8099:80
    app:
        image: laravel/docker
        container_name: ${APP_NAME}-php
        restart: always
        build:
            context: .
            dockerfile: .docker/php_composer/Dockerfile
        volumes:
            -   ./:/var/www
        depends_on:
            - db
    db:
        image: postgres
        restart: always
        container_name: ${APP_NAME}-db
        ports:
            - ${OUTER_DB_PORT}:${DB_PORT}
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - /var/lib/postgresql/data
    redis:
        image: redis
        container_name: ${APP_NAME}-redis
        restart: always
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        volumes:
            -   type: volume
                source: redis_data
                target: /var/lib/redis
            - /data/
        command:
            - 'redis-server'
            - '--loglevel ${REDIS_LOGLEVEL:-warning}'
        expose:
            - 6379

volumes:
    redis_data:
